version: "3"

services:
  app:
   build:
     context: ./bin/app
   networks:
     default: {}
   links:
    - mysql
   image: app:latest
   container_name: 'vmebel-app'
   restart: 'always'
   ports:
     - "${APP_PORT-80}:5000"
   volumes:
     - ${APP_DIR-./app}:/usr/src/app
  mysql:
    build: ./bin/mysql
    networks:
      default: {}
    container_name: 'vmebel-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

networks:
  default:
    name: ${NETWORK}
